# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: SCALACTIC_FILL_FILE_PATHNAMES=yes sbt "testOnly akka.ServerTest" #sbt clean coverage test #"testOnly domain.DomainUnitTest"
    - name: Generate report
      run: sbt coverageReport
    - name: Upload coverage to GitHubPage
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/scala-3.2.0/scoverage-report # The folder the action should deploy.
        branch: coverage-deploy
    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: code-coverage-report
    #     path: target/scala-3.2.0/scoverage-report
